### ISSUE TITLE
Adding standard `debug` logger

### ISSUE THREAD

**Issue by TimBeyer** [daddy-cool/highlogger#19]
I think it would be great if there could also be a standard `debug` log function which works just like all the other logging functions.
The filtering is super useful, but for a small server you usually do not need it, and the dispatching code to `highlogger` gets a lot more complicated if you cannot just call `logger.debug` but need to have a separate debug object.  
Plus I find it a bit confusing what I need to pass into `getDebug` if I don't care about prefixes at all.

**Comment by daddy-cool** [comment]
Good point. Thanks for the feedback I will implement this in the next update!

**Comment by daddy-cool** [comment]
See if https://github.com/daddy-cool/highlogger/pull/20 solves this.

**Comment by TimBeyer** [comment]
Awesome, you're quick mate :)

**Comment by daddy-cool** [comment]
trying my best :) v2.4.0 is live now!

**Comment by TimBeyer** [comment]
Thanks a lot, this came just at the right time :)
A day later and I would have probably removed all of the verbose logging from my application because it was spamming 'info'.
