### ISSUE TITLE
Extract syslog client

### ISSUE THREAD

**Issue by TimBeyer** [daddy-cool/highlogger#32]
I'm currently migrating from highlogger to bunyan as you propose on the readme, but I've run into sort of a blocker:  
There is no good syslog support.  
 https://github.com/mcavage/node-bunyan-syslog looks sort of dead and does not compile anymore, so I wanted to proceed to build my own adapter.  

However, https://github.com/strongloop/modern-syslog and https://github.com/schamane/node-syslog both do not support custom hosts and ports, but I need to connect to syslog on a port other than 514, for example to set up my own mock server for integration tests so that it doesn't clash with the syslog that is installed on my system.

So the question is, would you be willing to release your syslog client as a separate library so it can be integrated with bunyan? So far I've had no complaints about the performance and I don't see why we'd necessarily need a native C version of it like all the other implementations.

**Comment by TimBeyer** [comment]
I just found https://github.com/paulgrove/node-syslog-client and https://github.com/myndzi/syslog2

Maybe those will be of help too.

**Comment by daddy-cool** [comment]
Sorry for the late response, I've kind of missed your issue. If you haven't found a fix this is what I'm currently using instead of highlogger for the better part of the year:
* "bunyan": "^1.8.12"
* "bunyan-syslog-udp": "^0.1.0"
